version: '3.4'

services:
  ebooklibrary:
    image: ebook
    container_name: ebooklibrary
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    networks:
      - internal
  nginx:
    image: nginx
    container_name: nginx_ebooklibrary
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - ebooklibrary
    networks:
      - internal
networks:
  internal:
    driver: bridge
